<a href="https://colab.research.google.com/github/SarkiMudboy/pytorch-learn/blob/main/ML_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.0.1+cu118


In [ ]:
scalar = torch.tensor(7)

In [ ]:
scalar

tensor(7)

In [ ]:
scalar.ndim
scalar.shape

torch.Size([])

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
zero = torch.tensor(0)

In [ ]:
zero

tensor(0)

In [ ]:
vector = torch.tensor([2, 4])
vector

tensor([2, 4])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
vector.ndim

1

In [ ]:
new_vector = torch.tensor([3, 4, 5, 2, 5])
new_vector

tensor([3, 4, 5, 2, 5])

In [ ]:
new_vector.shape

torch.Size([5])

## Matrix

In [ ]:
M = torch.tensor([[2, 4, 6],
                  [1, 3, 5],
                  [0, 0, 0]])
M

tensor([[2, 4, 6],
        [1, 3, 5],
        [0, 0, 0]])

In [ ]:
M.shape

torch.Size([3, 3])

In [ ]:
M.ndim

2

In [ ]:
M[0]

tensor([2, 4, 6])

In [ ]:
M[1]

tensor([1, 3, 5])

In [ ]:
M[2]

tensor([0, 0, 0])

In [ ]:
new_vector[0]

tensor(3)

In [ ]:
TENSOR = torch.tensor([
    [
        [2, 4, 5],
        [3, 6, 8]
     ],
    [
        [2, 3, 6],
        [0, 8, 9]
     ]
    ])
TENSOR

tensor([[[2, 4, 5],
         [3, 6, 8]],

        [[2, 3, 6],
         [0, 8, 9]]])

In [ ]:
TENSOR.shape

torch.Size([2, 2, 3])

In [ ]:
small = torch.tensor([[3, 4], [3, 2], [9, 8]])

In [ ]:
small

tensor([[3, 4],
        [3, 2],
        [9, 8]])

In [ ]:
small.shape

torch.Size([3, 2])

In [ ]:
random = torch.rand(3, 5)
random

tensor([[0.3400, 0.0068, 0.3967, 0.5681, 0.4793],
        [0.0624, 0.8378, 0.3228, 0.0382, 0.4632],
        [0.9265, 0.2361, 0.2402, 0.2797, 0.4541]])

In [ ]:
new_rn = torch.rand(0, 4)

In [ ]:
new_rn

tensor([], size=(0, 4))

In [ ]:
random.ndim

2

In [ ]:
random.shape

torch.Size([3, 5])

In [ ]:
new_rn = torch.rand(size=(5, 3, 5))

In [ ]:
new_rn

tensor([[[0.8007, 0.7883, 0.0539, 0.7345, 0.6912],
         [0.4995, 0.1377, 0.1352, 0.2289, 0.5702],
         [0.4034, 0.1539, 0.3765, 0.3102, 0.2230]],

        [[0.3999, 0.3461, 0.1811, 0.0253, 0.7739],
         [0.4953, 0.0494, 0.6026, 0.3369, 0.3370],
         [0.7732, 0.0355, 0.5292, 0.1684, 0.4167]],

        [[0.3679, 0.7409, 0.0255, 0.2963, 0.4341],
         [0.5742, 0.1757, 0.2793, 0.6920, 0.5179],
         [0.5592, 0.4939, 0.4710, 0.2547, 0.7340]],

        [[0.0519, 0.7713, 0.1819, 0.0855, 0.6093],
         [0.4003, 0.0903, 0.6138, 0.7381, 0.3511],
         [0.0870, 0.5971, 0.0256, 0.4082, 0.4855]],

        [[0.4042, 0.4342, 0.8501, 0.1615, 0.9478],
         [0.6566, 0.2741, 0.2782, 0.2023, 0.0496],
         [0.3602, 0.2452, 0.8630, 0.9696, 0.0721]]])

In [ ]:
torch.rand(3)

tensor([0.3484, 0.2230, 0.8268])

In [ ]:
new_rn.dtype

torch.float32

In [ ]:
vector.dtype


torch.int64

In [ ]:
scalar.dtype

torch.int64

In [ ]:
torch.rand(2, 3, 4, 5)

tensor([[[[0.2861, 0.4016, 0.8100, 0.1474, 0.4972],
          [0.8702, 0.6866, 0.8062, 0.3406, 0.8634],
          [0.8573, 0.0875, 0.5440, 0.0093, 0.8802],
          [0.0113, 0.9476, 0.1632, 0.7005, 0.5217]],

         [[0.4585, 0.5294, 0.1890, 0.1975, 0.9126],
          [0.0318, 0.4536, 0.0529, 0.1977, 0.8042],
          [0.7790, 0.1105, 0.9470, 0.8158, 0.0860],
          [0.0264, 0.3457, 0.7137, 0.1828, 0.5670]],

         [[0.7246, 0.6268, 0.1459, 0.1736, 0.5090],
          [0.6416, 0.8981, 0.4817, 0.6409, 0.2878],
          [0.7861, 0.2645, 0.8813, 0.5117, 0.0021],
          [0.8457, 0.2750, 0.0911, 0.4275, 0.1337]]],


        [[[0.5727, 0.5190, 0.8989, 0.4695, 0.5897],
          [0.1801, 0.2319, 0.1223, 0.1860, 0.1955],
          [0.2457, 0.6994, 0.0760, 0.1067, 0.3062],
          [0.4626, 0.2052, 0.0856, 0.8675, 0.7393]],

         [[0.8952, 0.3844, 0.7985, 0.9854, 0.9916],
          [0.6609, 0.0779, 0.8084, 0.2301, 0.2683],
          [0.4757, 0.6286, 0.3711, 0.2077, 0.0154],
  

## Zeros and Ones


In [ ]:
one_tensor = torch.ones_like(input=new_rn)
one_tensor

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [ ]:
one_tensor * new_rn

tensor([[[0.8007, 0.7883, 0.0539, 0.7345, 0.6912],
         [0.4995, 0.1377, 0.1352, 0.2289, 0.5702],
         [0.4034, 0.1539, 0.3765, 0.3102, 0.2230]],

        [[0.3999, 0.3461, 0.1811, 0.0253, 0.7739],
         [0.4953, 0.0494, 0.6026, 0.3369, 0.3370],
         [0.7732, 0.0355, 0.5292, 0.1684, 0.4167]],

        [[0.3679, 0.7409, 0.0255, 0.2963, 0.4341],
         [0.5742, 0.1757, 0.2793, 0.6920, 0.5179],
         [0.5592, 0.4939, 0.4710, 0.2547, 0.7340]],

        [[0.0519, 0.7713, 0.1819, 0.0855, 0.6093],
         [0.4003, 0.0903, 0.6138, 0.7381, 0.3511],
         [0.0870, 0.5971, 0.0256, 0.4082, 0.4855]],

        [[0.4042, 0.4342, 0.8501, 0.1615, 0.9478],
         [0.6566, 0.2741, 0.2782, 0.2023, 0.0496],
         [0.3602, 0.2452, 0.8630, 0.9696, 0.0721]]])

In [ ]:
z_tensor = torch.zeros_like(input=new_rn)
z_tensor

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [ ]:
z_tensor * new_rn

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [ ]:
ten = torch.range(2, 4)

<ipython-input-43-d94f1b23fb7b>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  ten = torch.range(2, 4)


In [ ]:
ten

tensor([2., 3., 4.])

In [ ]:
w = ten[0]
w

tensor(2.)

In [ ]:
w_zero = torch.zeros_like(input=w)
w_zero

tensor(0.)

In [ ]:
w_zero * ten

tensor([0., 0., 0.])

In [ ]:
w_zero.dtype

torch.float32

## Tensor Datatypes

In [ ]:
null_tensor = torch.tensor([3., 5., 7.])

In [ ]:
null_tensor.shape, null_tensor.dtype, null_tensor.requires_grad, null_tensor.device

(torch.Size([3]), torch.float32, False, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([45., 32., 44., 13.], dtype=torch.float16)
float_16_tensor

tensor([45., 32., 44., 13.], dtype=torch.float16)

In [ ]:
float_32_tensor = float_16_tensor.type(torch.float)
float_32_tensor

tensor([45., 32., 44., 13.])

In [ ]:
floatc128tensor = float_32_tensor.type(torch.complex128)
floatc128tensor

tensor([45.+0.j, 32.+0.j, 44.+0.j, 13.+0.j], dtype=torch.complex128)

In [ ]:
floatc128tensor.shape, null_tensor.shape
# null_tensor = torch.tensor([2, 3, 4, 5])

In [ ]:
math_op = floatc128tensor * null_tensor
math_op


tensor([ 90.+0.j,  96.+0.j, 176.+0.j,  65.+0.j], dtype=torch.complex128)

In [ ]:
null_tensor = null_tensor.type(torch.int8)
null_tensor

tensor([2, 3, 4, 5], dtype=torch.int8)

In [ ]:
math_op = floatc128tensor * null_tensor
math_op

tensor([ 90.+0.j,  96.+0.j, 176.+0.j,  65.+0.j], dtype=torch.complex128)

In [ ]:
null_tensor = null_tensor.type(torch.float16)
null_tensor

tensor([2., 3., 4., 5.], dtype=torch.float16)

In [ ]:
torch64_tensor = floatc128tensor.type(torch.float64)
torch64_tensor

<ipython-input-59-90d02f4e266a>:1: UserWarning: Casting complex values to real discards the imaginary part (Triggered internally at ../aten/src/ATen/native/Copy.cpp:276.)
  torch64_tensor = floatc128tensor.type(torch.float64)


tensor([45., 32., 44., 13.], dtype=torch.float64)

In [ ]:
math_op = torch64_tensor * null_tensor
math_op, torch64_tensor.dtype, null_tensor.dtype

(tensor([ 90.,  96., 176.,  65.], dtype=torch.float64),
 torch.float64,
 torch.float16)

In [ ]:
float32_tensor = torch64_tensor.type(torch.float)
float32_tensor

tensor([45., 32., 44., 13.])

In [ ]:
math_op = float32_tensor * null_tensor
math_op, float32_tensor.dtype, null_tensor.dtype

(tensor([ 90.,  96., 176.,  65.]), torch.float32, torch.float16)

In [ ]:
float32_tensor.device, null_tensor.device

(device(type='cpu'), device(type='cpu'))

In [ ]:
float32_tensor = torch.tensor([ 90.,  96., 176.,  65.], dtype=torch.float, device=torch.device('cuda'))
float32_tensor

tensor([ 90.,  96., 176.,  65.], device='cuda:0')

In [ ]:
math_op = float32_tensor * null_tensor
math_op, float32_tensor.dtype, null_tensor.dtype

RuntimeError: ignored