<a href="https://colab.research.google.com/github/SarkiMudboy/pytorch-learn/blob/main/New_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__

'2.0.1+cu118'

In [ ]:
# scalar
scalar = torch.tensor(2)
scalar

tensor(2)

In [ ]:
# get dimension
scalar.ndim

# get integer (2)
two = scalar.item()

In [ ]:
# print type
type(scalar)

torch.Tensor

In [ ]:
type(two)

int

In [ ]:
zero = torch.tensor(0)
zero

tensor(0)

In [ ]:
zero.ndim

0

In [ ]:
float_type = torch.tensor(0.23)
float_type

tensor(0.2300)

In [ ]:
float_type.ndim

0

In [ ]:
scalar.shape

torch.Size([])

In [ ]:
scalar

tensor(2)

In [ ]:
zero.shape

torch.Size([])

In [ ]:
float_type.shape

torch.Size([])

In [ ]:
# Vectors

vector = torch.tensor([[2, 3], [4, 5]])
vector

tensor([[2, 3],
        [4, 5]])

In [ ]:
print(vector.ndim, vector.shape)

2 torch.Size([2, 2])


In [ ]:
three_component_vector = torch.tensor([[1, 2], [3.4, 0.002], [1.2, 4]])
three_component_vector

tensor([[1.0000e+00, 2.0000e+00],
        [3.4000e+00, 2.0000e-03],
        [1.2000e+00, 4.0000e+00]])

In [ ]:
three_component_vector.shape

torch.Size([3, 2])

In [ ]:
irregular = torch.tensor([[2, 5, 6], [3, 3, 2]])
irregular.shape

torch.Size([2, 3])

In [ ]:
irregular.ndim

2

In [ ]:
one_d = torch.tensor([3, 4])
one_d

tensor([3, 4])

In [ ]:
one_d.ndim

1

In [ ]:
one_d.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[3, 4], [3, 4]])
MATRIX

tensor([[3, 4],
        [3, 4]])

In [ ]:
# MATRIX.item() -> bug

In [ ]:
detail = "first element -> %s" % MATRIX[0]
print(detail)

first element -> tensor([3, 4])


In [ ]:
MATRIX[0].ndim

1

In [ ]:
MATRIX[0].shape

torch.Size([2])

In [ ]:
TENSOR = torch.tensor([
    [
        [2, 4, 5],
        [3, 6, 8],
     ],
    [
        [2, 3, 6],
        [0, 8, 9]
     ],
    [
        [3, 1, 4],
        [0, 0, 3]
    ]
    ])
TENSOR

tensor([[[2, 4, 5],
         [3, 6, 8]],

        [[2, 3, 6],
         [0, 8, 9]],

        [[3, 1, 4],
         [0, 0, 3]]])

In [ ]:
TENSOR.shape

torch.Size([3, 2, 3])

In [ ]:
TENSOR.ndim

3

##Random tensors

In [ ]:
random_tensor = torch.rand(2)
print(random_tensor, random_tensor.shape)

tensor([0.1023, 0.8577]) torch.Size([2])


In [ ]:
random_tensor_2 = torch.rand(2, 3)
random_tensor_2

tensor([[0.0773, 0.8134, 0.6742],
        [0.4227, 0.0440, 0.7117]])

In [ ]:
random_tensor_3 = torch.rand(size=(21, 3, 11))
print(random_tensor_3, random_tensor_3.shape)

tensor([[[0.1371, 0.9055, 0.8073, 0.3904, 0.9987, 0.2981, 0.8093, 0.3721,
          0.8241, 0.6049, 0.4826],
         [0.3585, 0.9986, 0.5379, 0.6350, 0.5567, 0.3055, 0.1793, 0.1726,
          0.3466, 0.9611, 0.2596],
         [0.9268, 0.8524, 0.0043, 0.8556, 0.2240, 0.7805, 0.8401, 0.7898,
          0.9230, 0.8155, 0.6571]],

        [[0.1179, 0.7314, 0.7730, 0.4213, 0.4901, 0.6246, 0.2978, 0.4031,
          0.0677, 0.7734, 0.6080],
         [0.2717, 0.0133, 0.3957, 0.7970, 0.6050, 0.9376, 0.6701, 0.1499,
          0.0710, 0.8225, 0.0394],
         [0.1315, 0.2132, 0.6372, 0.9676, 0.4822, 0.9177, 0.5979, 0.5720,
          0.7753, 0.3036, 0.8037]],

        [[0.9214, 0.8232, 0.4381, 0.4932, 0.4830, 0.6918, 0.8579, 0.9464,
          0.4573, 0.2589, 0.7239],
         [0.6812, 0.5640, 0.4272, 0.4953, 0.5751, 0.2326, 0.9132, 0.2305,
          0.4023, 0.3153, 0.5698],
         [0.4186, 0.5019, 0.4653, 0.5904, 0.3356, 0.6354, 0.4021, 0.2931,
          0.3338, 0.1557, 0.2710]],

        [[0.2

In [ ]:
random_tensor_3.ndim

3

In [ ]:
random_tensor

tensor([0.1023, 0.8577])

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
new_rn = torch.rand(size=[2, 2, 2, 2])
print(new_rn, new_rn.dtype, new_rn.shape, new_rn.ndim)

tensor([[[[0.3133, 0.5229],
          [0.9528, 0.9083]],

         [[0.2968, 0.3060],
          [0.4585, 0.9617]]],


        [[[0.4217, 0.5514],
          [0.4003, 0.9636]],

         [[0.0973, 0.9742],
          [0.7709, 0.0359]]]]) torch.float32 torch.Size([2, 2, 2, 2]) 4


##Zeros and Ones

In [ ]:
zero_tensor = torch.zeros(size=(2, 2))
basic_zero = torch.tensor([[0, 0, 0], [0, 0, 0]])
print('zero ->', zero_tensor, 'data_type ->', zero_tensor.dtype)
print('zero ->', basic_zero, 'data_type ->', basic_zero.dtype)

zero -> tensor([[0., 0.],
        [0., 0.]]) data_type -> torch.float32
zero -> tensor([[0, 0, 0],
        [0, 0, 0]]) data_type -> torch.int64


In [ ]:
zero_2 = torch.zeros((3, 7, 8))
zero_2

tensor([[[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [ ]:
print(torch.zeros((2, 3, 0)))

tensor([], size=(2, 3, 0))


In [ ]:
test_tensor = torch.tensor([])

In [ ]:
test_tensor

tensor([])

In [ ]:
ones = torch.ones(size=[3, 4], dtype=torch.int64)
# creates a single tensor tensor([1.])
one_scalar = torch.ones(1)

print(ones, ones.dtype, one_scalar, one_scalar.ndim)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]) torch.int64 tensor([1.]) 1


In [ ]:
one_dim_tensor = torch.tensor(2)
# creates a scalar

In [ ]:
one_dim_tensor, one_dim_tensor.ndim

(tensor(2), 0)

## Tensors arange and Tensors like

In [ ]:
zero_to_five = torch.range(0, 5) # Deprecated
zero_to_five

<ipython-input-125-56bc1d1bf171>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_five = torch.range(0, 5) # Deprecated


tensor([0., 1., 2., 3., 4., 5.])

In [ ]:
five_to_twenty_five = torch.arange(5, 25, 2)
five_to_twenty_five

tensor([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [ ]:
import numpy as np
my_array = np.array([[2, 3, 4], [6, 4, 2]], dtype=np.float64)

def convert_np_array_to_tensor(array):

  return torch.tensor(array)

tensor_from_array = convert_np_array_to_tensor(my_array)
tensor_from_array, tensor_from_array.dtype

(tensor([[2., 3., 4.],
         [6., 4., 2.]], dtype=torch.float64),
 torch.float64)

In [ ]:
tensor = torch.tensor([])
index = list(tensor.shape)
tensor, tensor.ndim, tensor.shape, tensor.size(), index

(tensor([]), 1, torch.Size([0]), torch.Size([0]), [0])

In [ ]:
def build_tensor(size):

  size = list(size)
  input_range = size[1]
  tensor = torch.zeros(size=size)

  for n in range(size[0]):
    tensor[n] = torch.arange(input_range)

  return tensor

random = torch.rand([2, 3])
custom = build_tensor(random.shape)
custom

tensor([[0., 1., 2.],
        [0., 1., 2.]])

In [ ]:
new_one = torch.ones_like(custom)
new_zero = torch.zeros_like(new_one)

new_one, new_zero

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

## Tensor data types

In [ ]:
new_tensor = torch.rand(2, 3)
new_tensor, new_tensor.shape, new_tensor.dtype, new_tensor.device

(tensor([[0.3469, 0.4466, 0.3023],
         [0.9922, 0.8988, 0.6786]]),
 torch.Size([2, 3]),
 torch.float32,
 device(type='cpu'))

In [ ]:
float64_tensor = torch.tensor([[2.3, 4.5]], dtype=torch.double)
float64_tensor, float64_tensor.dtype, float64_tensor.device

(tensor([[2.3000, 4.5000]], dtype=torch.float64),
 torch.float64,
 device(type='cpu'))

In [ ]:
float_half = torch.ones_like(float64_tensor, dtype=torch.float16)
float_half, float_half.dtype, float_half.device

(tensor([[1., 1.]], dtype=torch.float16), torch.float16, device(type='cpu'))

In [ ]:
float_half = torch.ones_like(float64_tensor, dtype=torch.bfloat16)
float_half, float_half.dtype, float_half.device

(tensor([[1., 1.]], dtype=torch.bfloat16), torch.bfloat16, device(type='cpu'))

In [ ]:
complex_tensor = torch.rand(4, 6, dtype=torch.complex64)
complex_tensor, complex_tensor.dtype, complex_tensor.device

(tensor([[0.4615+0.8749j, 0.0040+0.9031j, 0.7141+0.2064j, 0.3616+0.7443j,
          0.3703+0.4643j, 0.3628+0.9258j],
         [0.5904+0.7396j, 0.1502+0.5978j, 0.4078+0.6864j, 0.2836+0.1270j,
          0.6011+0.6571j, 0.7482+0.9723j],
         [0.8821+0.4333j, 0.2621+0.1589j, 0.4776+0.6746j, 0.3828+0.0288j,
          0.5665+0.8466j, 0.3306+0.9746j],
         [0.8418+0.3601j, 0.1551+0.4387j, 0.9361+0.8612j, 0.4033+0.6064j,
          0.9151+0.0708j, 0.8645+0.6540j]]),
 torch.complex64,
 device(type='cpu'))

In [ ]:
complex_tensor_gpu = torch.rand(4, 6, dtype=torch.complex64, device=torch.device('cuda'))
complex_tensor_gpu, complex_tensor.dtype, complex_tensor_gpu.device

(tensor([[0.4760+0.6226j, 0.8223+0.2213j, 0.2301+0.4216j, 0.0536+0.2047j,
          0.8964+0.7725j, 0.8364+0.3517j],
         [0.3610+0.2944j, 0.7125+0.2238j, 0.3155+0.1499j, 0.5772+0.6571j,
          0.0274+0.7820j, 0.1361+0.0551j],
         [0.6351+0.4308j, 0.4172+0.5694j, 0.9088+0.7046j, 0.9461+0.9338j,
          0.2379+0.6276j, 0.5193+0.4485j],
         [0.3118+0.3800j, 0.2238+0.7239j, 0.5225+0.5251j, 0.5785+0.2976j,
          0.8956+0.5954j, 0.5352+0.8930j]], device='cuda:0'),
 torch.complex64,
 device(type='cuda', index=0))

In [ ]:
torch.device('cuda')

device(type='cuda')

In [ ]:
eight_tensor_signed = torch.tensor([[
                                      [2, 1, 4],
                                      [3, 5, 6]
                                      ],
                                      [
                                      [2.3, 5, 4],
                                      [3.11, 5, 6.1]
                                      ]], dtype=torch.int8)
eight_tensor_signed, eight_tensor_signed.dtype, torch.ones_like(complex_tensor_gpu)

(tensor([[[2, 1, 4],
          [3, 5, 6]],
 
         [[2, 5, 4],
          [3, 5, 6]]], dtype=torch.int8),
 torch.int8,
 tensor([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
         [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
         [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
         [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]], device='cuda:0'))

In [ ]:
new_ones = torch.ones((2, 5), dtype=torch.bool)
new_ones, new_ones.dtype

(tensor([[True, True, True, True, True],
         [True, True, True, True, True]]),
 torch.bool)

In [ ]:
new_zeros = torch.zeros((2, 5), dtype=torch.bool)
new_zeros, new_zeros.dtype

(tensor([[False, False, False, False, False],
         [False, False, False, False, False]]),
 torch.bool)

In [ ]:
float_16_tensor = torch.tensor([33., 32., 0., 0.], dtype=torch.float16)
float_16_tensor

tensor([33., 32.,  0.,  0.], dtype=torch.float16)

In [ ]:
float_128_tensor = float_16_tensor.type(torch.complex128)
float_128_tensor, float_128_tensor.dtype, float_128_tensor.requires_grad

(tensor([33.+0.j, 32.+0.j,  0.+0.j,  0.+0.j], dtype=torch.complex128),
 torch.complex128,
 False)

In [ ]:
torch_product = torch.mul(float_16_tensor, float_128_tensor)
torch_product, float_16_tensor.dtype, float_128_tensor.dtype

(tensor([1089.+0.j, 1024.+0.j,    0.+0.j,    0.+0.j], dtype=torch.complex128),
 torch.float16,
 torch.complex128)

In [ ]:
torch_product + 10

tensor([1099.+0.j, 1034.+0.j,   10.+0.j,   10.+0.j], dtype=torch.complex128)

In [ ]:
torch_product -10

tensor([1079.+0.j, 1014.+0.j,  -10.+0.j,  -10.+0.j], dtype=torch.complex128)

In [ ]:
torch_product = torch_product.type(torch.half)
torch_product

tensor([1089., 1024.,    0.,    0.], dtype=torch.float16)

In [ ]:
torch_product.divide(2)

tensor([544.5000, 512.0000,   0.0000,   0.0000], dtype=torch.float16)

In [ ]:
torch_product.device

device(type='cpu')

In [ ]:
my_tensor = torch.rand(4, 5, 6)
ones = torch.ones_like(my_tensor)
my_tensor, ones, my_tensor * ones

(tensor([[[0.3234, 0.6943, 0.5418, 0.2435, 0.0863, 0.6528],
          [0.0840, 0.7803, 0.9182, 0.6163, 0.5303, 0.8690],
          [0.0389, 0.1212, 0.6689, 0.5460, 0.5845, 0.5513],
          [0.5520, 0.6586, 0.2890, 0.1019, 0.2441, 0.5902],
          [0.4711, 0.9119, 0.5889, 0.7047, 0.0602, 0.8015]],
 
         [[0.6178, 0.0451, 0.2953, 0.7888, 0.1085, 0.0360],
          [0.6698, 0.0176, 0.2859, 0.1447, 0.2998, 0.0241],
          [0.5734, 0.8843, 0.1747, 0.8313, 0.8182, 0.2722],
          [0.2432, 0.6507, 0.5836, 0.7596, 0.4519, 0.6967],
          [0.8034, 0.5934, 0.0121, 0.3227, 0.0334, 0.3003]],
 
         [[0.6092, 0.5228, 0.2484, 0.4157, 0.4283, 0.2944],
          [0.3892, 0.5915, 0.9886, 0.6818, 0.2134, 0.3478],
          [0.4244, 0.3566, 0.3413, 0.4493, 0.0347, 0.3706],
          [0.8864, 0.1104, 0.0641, 0.7306, 0.5409, 0.6209],
          [0.3157, 0.0175, 0.5929, 0.4744, 0.4869, 0.1919]],
 
         [[0.2867, 0.4977, 0.7904, 0.9860, 0.9478, 0.6959],
          [0.1114, 0.7770, 0.31

## Tensor Multipilcation

In [ ]:
prd = my_tensor * ones
prd
# assert prd == my_tensor, 'Not what I expected'

tensor([[[0.3234, 0.6943, 0.5418, 0.2435, 0.0863, 0.6528],
         [0.0840, 0.7803, 0.9182, 0.6163, 0.5303, 0.8690],
         [0.0389, 0.1212, 0.6689, 0.5460, 0.5845, 0.5513],
         [0.5520, 0.6586, 0.2890, 0.1019, 0.2441, 0.5902],
         [0.4711, 0.9119, 0.5889, 0.7047, 0.0602, 0.8015]],

        [[0.6178, 0.0451, 0.2953, 0.7888, 0.1085, 0.0360],
         [0.6698, 0.0176, 0.2859, 0.1447, 0.2998, 0.0241],
         [0.5734, 0.8843, 0.1747, 0.8313, 0.8182, 0.2722],
         [0.2432, 0.6507, 0.5836, 0.7596, 0.4519, 0.6967],
         [0.8034, 0.5934, 0.0121, 0.3227, 0.0334, 0.3003]],

        [[0.6092, 0.5228, 0.2484, 0.4157, 0.4283, 0.2944],
         [0.3892, 0.5915, 0.9886, 0.6818, 0.2134, 0.3478],
         [0.4244, 0.3566, 0.3413, 0.4493, 0.0347, 0.3706],
         [0.8864, 0.1104, 0.0641, 0.7306, 0.5409, 0.6209],
         [0.3157, 0.0175, 0.5929, 0.4744, 0.4869, 0.1919]],

        [[0.2867, 0.4977, 0.7904, 0.9860, 0.9478, 0.6959],
         [0.1114, 0.7770, 0.3100, 0.5857, 0.5076, 

In [ ]:
zeros = torch.zeros_like(my_tensor)
zeros * my_tensor

tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]])

In [ ]:
new_tensor = torch.rand(list(my_tensor.shape))

In [ ]:
new_tensor

tensor([[[0.2059, 0.8166, 0.7151, 0.7288, 0.3289, 0.2491],
         [0.7174, 0.6440, 0.4636, 0.7188, 0.1335, 0.1584],
         [0.2272, 0.4985, 0.5132, 0.1942, 0.5148, 0.2661],
         [0.3198, 0.2519, 0.7603, 0.8701, 0.5646, 0.3593],
         [0.4978, 0.8997, 0.3544, 0.1346, 0.4657, 0.0423]],

        [[0.5018, 0.6995, 0.0862, 0.2878, 0.3554, 0.1843],
         [0.7668, 0.5241, 0.6118, 0.6440, 0.5955, 0.1189],
         [0.4538, 0.4724, 0.7777, 0.4774, 0.4376, 0.5469],
         [0.8766, 0.1268, 0.0511, 0.5755, 0.6696, 0.3394],
         [0.5215, 0.9932, 0.1281, 0.8494, 0.2909, 0.4085]],

        [[0.2192, 0.7642, 0.0166, 0.9381, 0.4788, 0.5422],
         [0.2098, 0.5831, 0.6405, 0.5703, 0.7584, 0.1381],
         [0.5228, 0.2690, 0.4896, 0.3828, 0.0841, 0.7823],
         [0.6997, 0.0432, 0.6333, 0.0785, 0.3666, 0.9074],
         [0.6823, 0.8223, 0.5385, 0.8934, 0.7453, 0.3662]],

        [[0.3983, 0.7730, 0.4459, 0.9204, 0.0018, 0.4389],
         [0.6808, 0.2928, 0.2825, 0.3044, 0.7145, 

In [ ]:
one = torch.tensor([0., 0.], dtype=torch.bool)
two = torch.tensor([5., 6.])
one, two, one * two

(tensor([False, False]), tensor([5., 6.]), tensor([0., 0.]))

In [ ]:
scalar = torch.tensor(3)
scalar

tensor(3)

In [ ]:
test_tensor = torch.rand(2, 3, dtype=torch.float64)
test_tensor

tensor([[0.4669, 0.5975, 0.1979],
        [0.7964, 0.4051, 0.8858]], dtype=torch.float64)

In [ ]:
scalar * test_tensor

tensor([[1.4006, 1.7924, 0.5937],
        [2.3892, 1.2152, 2.6575]], dtype=torch.float64)

In [ ]:
test_tensor = torch.ones_like(test_tensor)
test_tensor, scalar * test_tensor

(tensor([[1., 1., 1.],
         [1., 1., 1.]], dtype=torch.float64),
 tensor([[3., 3., 3.],
         [3., 3., 3.]], dtype=torch.float64))

### Tensor Multipilcation (Element-wise)

In [ ]:
%%time
tensor_1 = torch.rand(3, 5)
tensor_2 = torch.rand(2, 4)
tensor_1, tensor_2

CPU times: user 396 µs, sys: 1.79 ms, total: 2.19 ms
Wall time: 27.6 ms


(tensor([[0.4145, 0.5167, 0.6690, 0.8338, 0.9729],
         [0.9897, 0.5788, 0.4116, 0.6187, 0.8709],
         [0.0424, 0.9873, 0.4666, 0.8853, 0.2595]]),
 tensor([[0.2972, 0.7827, 0.5899, 0.9354],
         [0.9360, 0.4438, 0.3866, 0.2527]]))

In [ ]:
%%time
tensor_1 * torch.tensor(2)

CPU times: user 836 µs, sys: 0 ns, total: 836 µs
Wall time: 1.02 ms


tensor([[0.8290, 1.0334, 1.3380, 1.6676, 1.9459],
        [1.9794, 1.1576, 0.8232, 1.2373, 1.7418],
        [0.0848, 1.9747, 0.9332, 1.7707, 0.5190]])

In [ ]:
torch.tensor(2).item()

2

In [ ]:
%%time
torch.mul(tensor_1, torch.tensor(2))

CPU times: user 496 µs, sys: 0 ns, total: 496 µs
Wall time: 389 µs


tensor([[0.6083, 0.5975, 1.5675, 0.2653, 1.9504],
        [1.8410, 1.5157, 0.8377, 1.5304, 0.9477],
        [0.0769, 1.1033, 0.0369, 0.2127, 1.5816]])

In [ ]:
%%time
torch.rand(2, 12) * torch.tensor(33)

CPU times: user 1.11 ms, sys: 0 ns, total: 1.11 ms
Wall time: 1.13 ms


tensor([[21.9190, 17.5076, 26.0585, 15.3886,  4.1364, 31.4186, 11.6925, 25.9084,
         31.9482,  8.7306, 32.7608, 13.2136],
        [29.8148, 22.3713, 28.6131, 17.6481, 11.5470, 16.2106,  3.1269, 20.5407,
         31.6644, 30.0398,  4.3947, 25.0345]])

In [ ]:
%%time
torch.mul(torch.rand(2, 12), torch.tensor(33))

CPU times: user 940 µs, sys: 0 ns, total: 940 µs
Wall time: 897 µs


tensor([[ 3.5309, 16.2808, 32.6614, 32.3542, 29.5044, 15.5081, 19.9080,  0.8257,
         18.4309,  8.0749, 11.6826,  7.2572],
        [14.9721, 23.7253,  1.7154,  5.6716, 29.5928, 15.1006, 24.3449, 20.8694,
          6.4289,  0.7993, 27.2143, 24.4847]])

In [ ]:
tensor_1 = torch.rand(size=(4, 7), dtype=torch.float32)
tensor_2 = torch.rand(size=(4, 7))
tensor_1, tensor_2

(tensor([[0.8078, 0.8859, 0.0250, 0.2911, 0.5541, 0.7143, 0.8717],
         [0.0215, 0.4289, 0.7971, 0.9714, 0.9511, 0.2420, 0.3203],
         [0.1786, 0.1712, 0.2196, 0.5974, 0.6805, 0.0940, 0.9199],
         [0.7488, 0.6560, 0.5169, 0.6928, 0.6396, 0.9322, 0.0729]]),
 tensor([[0.5610, 0.0389, 0.0172, 0.6395, 0.7046, 0.0860, 0.4377],
         [0.0891, 0.3409, 0.7961, 0.7285, 0.3183, 0.1105, 0.2170],
         [0.7292, 0.6331, 0.3150, 0.1028, 0.6603, 0.3442, 0.2880],
         [0.7552, 0.7045, 0.3818, 0.4569, 0.6030, 0.3700, 0.8328]]))

In [ ]:
tensor_1 * tensor_2

tensor([[4.5319e-01, 3.4492e-02, 4.2853e-04, 1.8616e-01, 3.9040e-01, 6.1448e-02,
         3.8155e-01],
        [1.9179e-03, 1.4622e-01, 6.3462e-01, 7.0772e-01, 3.0269e-01, 2.6746e-02,
         6.9495e-02],
        [1.3027e-01, 1.0840e-01, 6.9169e-02, 6.1446e-02, 4.4932e-01, 3.2364e-02,
         2.6491e-01],
        [5.6551e-01, 4.6214e-01, 1.9736e-01, 3.1655e-01, 3.8569e-01, 3.4488e-01,
         6.0741e-02]])

In [ ]:
simple_tensor_1 = torch.tensor([[2, 1], [3, 2]], dtype=torch.int)
simple_tensor_2 = torch.tensor([[3, 3], [1, 4]], dtype=torch.int)
simple_tensor_1, simple_tensor_2, torch.mul(simple_tensor_1, simple_tensor_2)

(tensor([[2, 1],
         [3, 2]], dtype=torch.int32),
 tensor([[3, 3],
         [1, 4]], dtype=torch.int32),
 tensor([[6, 3],
         [3, 8]], dtype=torch.int32))

In [ ]:
vector = torch.arange(2)

### Matrix multipilcation

In [ ]:
vec = torch.arange(5)
vec_2 = torch.arange(5)
vec, vec_2

(tensor([0, 1, 2, 3, 4]), tensor([0, 1, 2, 3, 4]))

In [ ]:
%%time
torch.matmul(vec, vec_2)

CPU times: user 12 µs, sys: 1 ms, total: 1.02 ms
Wall time: 1.09 ms


tensor(30)

In [ ]:
vec.shape, vec_2.shape

(torch.Size([5]), torch.Size([5]))

In [ ]:
%%time
vec = torch.arange(39)
vec_2 = torch.arange(39)
torch.matmul(vec, vec_2)

CPU times: user 1.26 ms, sys: 13 µs, total: 1.27 ms
Wall time: 1.02 ms


tensor(19019)

In [ ]:
%%time
tensor_1 = torch.rand(2, 3)
tensor_2 = torch.rand(3, 2)
tensor_1, tensor_2, torch.matmul(tensor_1, tensor_2)

CPU times: user 1.42 ms, sys: 44 µs, total: 1.46 ms
Wall time: 18.4 ms


(tensor([[0.4896, 0.4941, 0.0408],
         [0.9320, 0.7358, 0.1328]]),
 tensor([[0.2059, 0.8870],
         [0.7525, 0.4180],
         [0.7579, 0.0562]]),
 tensor([[0.5036, 0.6431],
         [0.8463, 1.1417]]))

In [ ]:
%%time
tensor_1 = torch.tensor([[2, 3], [3, 4]])
tensor_2 = torch.tensor([[4, 1], [2, 2]])
tensor_1, tensor_2, torch.matmul(tensor_1, tensor_2)

CPU times: user 1.23 ms, sys: 18 µs, total: 1.24 ms
Wall time: 4.95 ms


(tensor([[2, 3],
         [3, 4]]),
 tensor([[4, 1],
         [2, 2]]),
 tensor([[14,  8],
         [20, 11]]))

In [ ]:
tensor_1.shape, tensor_2.shape

(torch.Size([2, 2]), torch.Size([2, 2]))

In [ ]:
%%time
tensor_1 = torch.rand(2, 43)
tensor_2 = torch.rand(43, 5)
tensor_1 @ tensor_2

CPU times: user 326 µs, sys: 905 µs, total: 1.23 ms
Wall time: 1.02 ms


tensor([[12.0901, 10.8817, 10.5343, 10.7485, 10.0208],
        [11.3665, 11.6322, 10.7962, 11.5580, 10.8697]])

In [ ]:
%%time
tensor_1 = torch.rand(22, 3)
tensor_2 = torch.rand(3, 22)
product = torch.matmul(tensor_1, tensor_2)
product

CPU times: user 181 µs, sys: 9 µs, total: 190 µs
Wall time: 205 µs


tensor([[1.1348, 0.5953, 0.9516, 0.8821, 0.7381, 0.5609, 1.2333, 0.8302, 1.0312,
         0.7454, 0.9472, 0.3166, 1.1264, 0.3742, 0.6721, 1.1593, 0.6877, 0.4973,
         0.5211, 0.9584, 0.8408, 0.6624],
        [1.1156, 0.5457, 0.9267, 0.8869, 0.5987, 0.5204, 1.1363, 0.8154, 1.0756,
         0.6093, 0.8560, 0.2370, 1.1177, 0.3861, 0.6075, 1.1018, 0.6389, 0.4856,
         0.4102, 0.8562, 0.8492, 0.6595],
        [0.9252, 0.5278, 0.7822, 0.5578, 0.9002, 0.4736, 1.1531, 0.5607, 0.6371,
         0.9356, 0.9443, 0.4221, 0.8866, 0.2196, 0.7059, 0.9649, 0.6043, 0.3374,
         0.6582, 0.9744, 0.6054, 0.5230],
        [0.6863, 0.4815, 0.6034, 0.5129, 0.7908, 0.4396, 0.9612, 0.5379, 0.4725,
         0.7752, 0.7782, 0.3960, 0.6551, 0.1891, 0.5413, 0.8238, 0.5290, 0.3314,
         0.5942, 0.8154, 0.4545, 0.3773],
        [0.9963, 0.5569, 0.8485, 0.9980, 0.4806, 0.5488, 1.0360, 0.9305, 1.0871,
         0.4271, 0.7405, 0.1982, 1.0152, 0.4258, 0.4633, 1.0869, 0.6296, 0.5624,
         0.3344, 0.743

In [ ]:
%%time
ones_tensor = torch.ones_like(product)
ones_tensor @ ones_tensor

CPU times: user 181 µs, sys: 0 ns, total: 181 µs
Wall time: 186 µs


tensor([[22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22.,
         22., 22., 22., 22., 22., 22., 22., 22.],
        [22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22.,
         22., 22., 22., 22., 22., 22., 22., 22.],
        [22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22.,
         22., 22., 22., 22., 22., 22., 22., 22.],
        [22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22.,
         22., 22., 22., 22., 22., 22., 22., 22.],
        [22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22.,
         22., 22., 22., 22., 22., 22., 22., 22.],
        [22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22.,
         22., 22., 22., 22., 22., 22., 22., 22.],
        [22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22.,
         22., 22., 22., 22., 22., 22., 22., 22.],
        [22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22., 22.,
         22., 22.,

In [ ]:
%%time
tensor_x = torch.tensor([2, 3, 4])
val = 0
for i in range(len(tensor_x)):
  val += (tensor_x[i] * tensor_x[i])
val

CPU times: user 2.79 ms, sys: 3.45 ms, total: 6.23 ms
Wall time: 91.7 ms


tensor(29)

In [ ]:
%%time
tensor_x * tensor_x

CPU times: user 99 µs, sys: 0 ns, total: 99 µs
Wall time: 103 µs


tensor([ 4,  9, 16])

In [ ]:
%%time
tensor_x @ tensor_x

CPU times: user 120 µs, sys: 7 µs, total: 127 µs
Wall time: 130 µs


tensor(29)

In [ ]:
%%time
torch.matmul(tensor_x, tensor_x)

CPU times: user 76 µs, sys: 4 µs, total: 80 µs
Wall time: 83 µs


tensor(29)

In [ ]:
# simulate http://matrixmultiplication.xyz/ matrix multiplication

mat_1 = torch.tensor([[5, 2],
                      [0, 4],
                      [22, 3]])
mat_2 = torch.tensor([2, 6])
mat_1, mat_2

(tensor([[ 5,  2],
         [ 0,  4],
         [22,  3]]),
 tensor([2, 6]))

In [ ]:
torch.mul(mat_1, mat_2)

tensor([[10, 12],
        [ 0, 24],
        [44, 18]])

In [ ]:
mat_1.shape, mat_2.shape

(torch.Size([3, 2]), torch.Size([2]))

In [ ]:
torch.matmul(mat_1, mat_2)

tensor([22, 24, 62])

 let's mask a bit

In [ ]:
tensor = torch.rand(3, 3)
tensor

tensor([[0.5158, 0.4150, 0.9689],
        [0.5845, 0.7943, 0.5193],
        [0.7568, 0.7836, 0.8469]])

In [ ]:
zeros = torch.zeros_like(tensor[2])
zeros

tensor([0., 0., 0.])

In [ ]:
tensor * zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
copy_tensor = tensor
copy_tensor[2] = zeros
copy_tensor

tensor([[0.5158, 0.4150, 0.9689],
        [0.5845, 0.7943, 0.5193],
        [0.0000, 0.0000, 0.0000]])

In [ ]:
tensor = torch.rand(2, 3)
tensor_1 = torch.rand(2, 3)
tensor, tensor_1

(tensor([[0.6983, 0.4093, 0.7767],
         [0.2243, 0.0609, 0.5830]]),
 tensor([[0.2311, 0.7938, 0.5845],
         [0.7653, 0.0574, 0.3778]]))

In [ ]:
print(f" tensor : \n {tensor} shape: {tensor.shape} and tensor_1: \n {tensor_1} shape: {tensor_1.shape}")
print("transposing tensor_2 .....")
tensor_2 = tensor_1.T
print("Transposed tensor: \n", tensor_2)
print(f" tensor : \n {tensor} shape: {tensor.shape} and tensor_2: \n {tensor_2}shape: {tensor_2.shape}")
print("Multiplying tensor and tensor_2......")
print("tensor @ tensor_2 = " + "\n", tensor @ tensor_2)

 tensor : 
 tensor([[0.6983, 0.4093, 0.7767],
        [0.2243, 0.0609, 0.5830]]) shape: torch.Size([2, 3]) and tensor_1: 
 tensor([[0.2311, 0.7938, 0.5845],
        [0.7653, 0.0574, 0.3778]]) shape: torch.Size([2, 3])
transposing tensor_2 .....
Transposed tensor: 
 tensor([[0.2311, 0.7653],
        [0.7938, 0.0574],
        [0.5845, 0.3778]])
 tensor : 
 tensor([[0.6983, 0.4093, 0.7767],
        [0.2243, 0.0609, 0.5830]]) shape: torch.Size([2, 3]) and tensor_2: 
 tensor([[0.2311, 0.7653],
        [0.7938, 0.0574],
        [0.5845, 0.3778]])shape: torch.Size([3, 2])
Multiplying tensor and tensor_2......
tensor @ tensor_2 = 
 tensor([[0.9403, 0.8513],
        [0.4410, 0.3955]])


In [ ]:
tensor_1 = torch.rand(1, 3, 3)
tensor_2 = torch.rand(1, 3, 3)
print(tensor_1, tensor_2)
print(tensor_1.shape, tensor_2.shape)
print(tensor_1 @ tensor_2)

tensor([[[0.8145, 0.0438, 0.7003],
         [0.4157, 0.1458, 0.1823],
         [0.0063, 0.2778, 0.5862]]]) tensor([[[0.1024, 0.5488, 0.9975],
         [0.8329, 0.7298, 0.1655],
         [0.8929, 0.7273, 0.4768]]])
torch.Size([1, 3, 3]) torch.Size([1, 3, 3])
tensor([[[0.7452, 0.9883, 1.1536],
         [0.3268, 0.4671, 0.5257],
         [0.7554, 0.6325, 0.3318]]])


In [ ]:
tensor_2 = tensor_2.T
print(tensor_2, tensor_2.shape)
print(torch.matmul(tensor_1, tensor_2))

tensor([[[0.8258],
         [0.9785]],

        [[0.4688],
         [0.4676]],

        [[0.6265],
         [0.4578]]]) torch.Size([3, 2, 1])


RuntimeError: ignored

In [ ]:
tbt_matrix = torch.rand(3, 3)
tbt_matrix_2 = torch.rand(size=(3, 3))
tbt_matrix, tbt_matrix_2

(tensor([[0.6167, 0.9229, 0.3776],
         [0.8804, 0.7708, 0.5336],
         [0.4101, 0.2936, 0.3587]]),
 tensor([[0.7455, 0.8445, 0.9197],
         [0.3432, 0.6115, 0.9003],
         [0.0791, 0.9869, 0.7091]]))

In [ ]:
torch.mm(tbt_matrix, tbt_matrix_2)

tensor([[0.8064, 1.4578, 1.6659],
        [0.9631, 1.7414, 1.8821],
        [0.4349, 0.8799, 0.8959]])

In [ ]:
# def multiply_matrices(matrix_1, matrix_2):
#   matrix_1_shape = matrix_1.shape
#   matrix_2_shape = matrix_2.shape

#   if matrix_1.shape[-1] != matrix_2.shape[0]:

#     transpose_mat_2 = matrix_2.T
#     transpose_mat_1 = matrix_2.T

#   if matrix_1.shape[-1] == transpose_mat_2.shape[0]:
#     pass

#   if transpose_mat_1.shape[-1] == matrix_2.shape[0]:
#     pass

#   if transpose_mat_1.shape[-1] == transpose_mat_2.shape[0]:
#     pass

  # fill the empty matrix shape with ones

In [ ]:
tensor_1 = torch.rand(2, 3)
tensor_2 = torch.rand(3, 4)
tensor_2.T.shape

torch.Size([4, 3])

In [ ]:
t = torch.tensor([2, 4, 5, 6])
t

tensor([2, 4, 5, 6])